---
# tasks file for ocp4 install

- name: mkdir ~/.kube
  file:
    path: ~/.kube
    state: directory

- name: Install kubeconfig
  copy:
    src: "{{ workdir }}/auth/kubeconfig"
    dest: "~/.kube/config"

# Run approve command till we have all workers ready. 'xargs -r ' is used to ignore empty stdin.
- name: Approve Worker CSRs
  shell: |
    oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs -r oc adm certificate approve
  until: lookup('pipe','oc get nodes | grep -w worker | grep -w Ready | wc -l') == worker_count
  retries: 20
  delay: 30

- name: Wait for install-complete
  shell: "openshift-install wait-for install-complete --log-level {{ log_level }}"
  args:
    chdir: "{{ workdir }}"

- name: Configure nfs-provisioner
  shell: helpernodecheck nfs-setup
  when: storage_type == "nfs"

# The image-registry is not always available immediately after the OCP installer
- name: Wait for image-registry operator
  shell: "oc get configs.imageregistry.operator.openshift.io/cluster --no-headers | wc -l"
  register: imgreg_operator_count
  until: imgreg_operator_count.stdout|int > 0
  retries: 20
  delay: 30

- name: Create and patch image-registry operator as registry-pvc
  tags: image-registry
  shell: |
    oc create -f /usr/local/src/registry-pvc.yaml -n openshift-image-registry
    oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{ "claim": "registry-pvc"}}, "managementState": "Managed"}}'
  when: storage_type == "nfs"

- name: Patch image-registry operator as emptyDir
  tags: image-registry
  shell: |
    oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}, "managementState": "Managed"}}'
  when: storage_type != "nfs"

- name: Force install kubeconfig again
  copy:
    src: "{{ workdir }}/auth/kubeconfig"
    dest: "~/.kube/config"
    force: yes
